# Generated by Django 5.1.7 on 2025-05-18 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_cajerousuarioespera_cajero'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'CAJA',
                'ordering': ['numero'],
            },
        ),
        migrations.DeleteModel(
            name='Cajero',
        ),
        migrations.AddField(
            model_name='user',
            name='is_cajero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='cajero',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cajero': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas', to=settings.AUTH_USER_MODEL),
        ),
    ]
