# Generated by Django 5.2.1 on 2025-07-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_password_administrador_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='password',
        ),
    ]
