# Generated by Django 5.1.7 on 2025-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_caja_delete_cajero_user_is_cajero_user_is_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('etiqueta', models.CharField(max_length=50)),
                ('prioridad', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'SERVICIO',
                'ordering': ['id'],
            },
        ),
    ]
