# Generated by Django 5.1.7 on 2025-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_administrador_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_simple',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')], default='cliente', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
