# Generated by Django 5.1.7 on 2025-07-21 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rol_simple'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='rol',
            name='Empleado',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='cliente',
        ),
        migrations.AddField(
            model_name='rol',
            name='nombre',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol_simple',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')], max_length=20, null=True, verbose_name='Rol del usuario'),
        ),
        migrations.AlterModelTable(
            name='rol',
            table='ROL',
        ),
    ]
