# Generated by Django 5.1.7 on 2025-07-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rol_options_remove_rol_empleado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='ID_Caja',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='EMPLEADO',
        ),
    ]
