# Generated by Django 5.1.7 on 2025-07-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_rol_simple_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_simple',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')], max_length=20, null=True, verbose_name='Rol del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.rol'),
        ),
    ]
