# Generated by Django 5.1.7 on 2025-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_rol_simple_alter_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol_simple',
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')], max_length=20, null=True, verbose_name='Rol del usuario'),
        ),
    ]
