# Generated by Django 5.1.7 on 2025-07-22 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_rol_simple_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='ID_Usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
