# Generated by Django 5.1.7 on 2025-07-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre de la caja')),
                ('Estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'CAJA',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('productos_vendidos', models.TextField(blank=True, default='[]')),
                ('fecha_factura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora_llegada', models.DateTimeField()),
                ('Hora_atencion', models.DateTimeField()),
                ('Hora_salida', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Prioridad', models.IntegerField()),
                ('Descripcion', models.TextField()),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula_manual', models.CharField(max_length=12)),
                ('numero_turno', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('en_atencion', 'En Atención'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='esperando', max_length=20)),
                ('es_prioritario', models.BooleanField(default=False)),
                ('posicion_cola', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'TURNO',
                'ordering': ['posicion_cola', 'created_at'],
            },
        ),
    ]
