# Generated by Django 5.1.7 on 2025-05-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cajerousuarioespera',
            name='cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cajero'),
        ),
        migrations.AddField(
            model_name='usuarioespera',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cajerousuarioespera',
            name='usuario_espera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.usuarioespera'),
        ),
        migrations.AlterUniqueTogether(
            name='cajerousuarioespera',
            unique_together={('cajero', 'usuario_espera')},
        ),
    ]
