# Generated by Django 5.2.1 on 2025-05-24 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ID_Cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.cliente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='ID_Servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.servicio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='Turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tickets.turno'),
        ),
    ]
