# Generated by Django 5.2.1 on 2025-07-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
