# Generated by Django 5.1.7 on 2025-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
