# Generated by Django 5.2.1 on 2025-07-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_servicio_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='turno',
            name='ID_Horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.horario'),
        ),
    ]
