# Generated by Django 5.1.7 on 2025-07-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_turno_deleted_at_remove_turno_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='Nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
