# Generated by Django 5.1.7 on 2025-07-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_servicio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='Descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Estado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
