# Generated by Django 5.1.7 on 2025-07-21 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_servicio_descripcion_alter_servicio_estado_and_more'),
        ('users', '0006_alter_empleado_options_remove_empleado_id_caja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['id'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AddField(
            model_name='caja',
            name='ID_Empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.empleado', unique=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='caja',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='caja',
            table='CAJA',
        ),
    ]
