# Generated by Django 5.1.7 on 2025-07-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_caja_options_caja_id_empleado_caja_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
