# Generated by Django 5.1.7 on 2025-07-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_caja_id_empleado_caja_id_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['posicion_cola', 'created_at'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='turno',
            name='es_prioritario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('esperando', 'Esperando'), ('en_atencion', 'En Atención'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='esperando', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='numero_turno',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='posicion_cola',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='ID_Caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.caja'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='ID_Horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.horario'),
        ),
        migrations.AlterModelTable(
            name='turno',
            table='TURNO',
        ),
    ]
