# Generated by Django 5.1.7 on 2025-07-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_turno_options_turno_es_prioritario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Cantidad_Producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Producto',
        ),
        migrations.AddField(
            model_name='factura',
            name='ID_Turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='tickets.turno'),
        ),
        migrations.AddField(
            model_name='factura',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='productos_vendidos',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_old', to='tickets.turno'),
        ),
    ]
