# Generated by Django 5.1.7 on 2025-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_factura_options_and_more'),
    ]

    operations = [
        # Add the nombre field (will be faked since it already exists)
        migrations.AddField(
            model_name='caja',
            name='nombre',
            field=models.CharField(default='A', max_length=10, unique=True, verbose_name='Nombre de la caja'),
            preserve_default=False,
        ),
        # Update model options
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['nombre'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
    ]
