# Generated by Django 5.2.1 on 2025-05-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(verbose_name=100)),
                ('Descripcion', models.CharField(verbose_name=300)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Marca', models.CharField(verbose_name=200)),
            ],
        ),
    ]
