# Generated by Django 5.1.7 on 2025-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producto_activo_producto_codigo_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requiere_orden_medica',
            field=models.BooleanField(default=False),
        ),
    ]
